name: flog
description: FLOG project

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_native_splash: ^2.3.1 # 로딩 화면 커스텀

  cupertino_icons: ^1.0.2
  camera: ^0.10.5+2
  path_provider: ^2.0.5
  image_picker: ^0.8.4+3
  intl: ^0.18.1
  
  firebase_core: ^2.15.0
  
  firebase_auth: ^4.7.2
  fluttertoast: ^8.2.2
  firebase_core_platform_interface: ^4.8.0
  cloud_firestore: ^4.8.4
  firebase_storage: ^11.2.5
  firebase_messaging: ^14.6.5
  flutter_local_notifications: ^15.1.0+1

  kakao_flutter_sdk_user: ^1.5.0 # 카카오 로그인


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/app_logo.png
    - assets/face_angry.png
    - assets/face_dizzy.png
    - assets/face_sad.png
    - assets/flog_coin_green.png
    - assets/flog_coin_yellow.png
    - assets/flog_foot_black.png
    - assets/flog_foot_green.png
    - assets/flog_foot_stroke.png
    - assets/flog_foot_white.png
    - assets/flog_logo.png
    - assets/flog_name.png
    - assets/flog_name_3d.png
    - button/back_arrow.png
    - button/book.png
    - button/checked.png
    - button/close.png
    - button/flash.png
    - button/flip.png
    - button/floging_fill.png
    - button/floging_line.png
    - button/memorybox_fill.png
    - button/memorybox_line.png
    - button/padlock.png
    - button/plus.png
    - button/qpuzzle_empty.png
    - button/qpuzzle_fill.png
    - button/qpuzzle_line.png
    - button/send_black.png
    - button/send_green.png
    - button/send_white.png
    - button/setting_fill.png
    - button/setting_line.png
    - button/shooting.png
    - button/sticker.png
    - button/text.png
    - button/video.png
